insert into PRODUCT(ID, NAME, CATEGORY, VALUE) VALUES(1, 'BodeBrown IPA', 'perecivel', 15.90);
insert into PRODUCT(ID, NAME, CATEGORY, VALUE) VALUES(2, 'Belorizontina', 'nao_perecivel', 8.90);
insert into PRODUCT(ID, NAME, CATEGORY, VALUE) VALUES(3, 'Mal Pale Ale', 'perecivel', 12.50);
insert into PRODUCT(ID, NAME, CATEGORY, VALUE) VALUES(4, 'Mal Pilsen', 'perecivel', 13.50);
insert into PRODUCT(ID, NAME, CATEGORY, VALUE) VALUES(5, 'Mal IPA', 'perecivel', 14.50);
insert into PRODUCT(ID, NAME, CATEGORY, VALUE) VALUES(6, 'Mal Double IPA', 'perecivel', 15.50);
insert into PRODUCT(ID, NAME, CATEGORY, VALUE) VALUES(7, 'Mal Imperial IPA', 'perecivel', 16.50);
insert into PRODUCT(ID, NAME, CATEGORY, VALUE) VALUES(8, 'Mal Stout', 'perecivel', 17.50);
insert into PRODUCT(ID, NAME, CATEGORY, VALUE) VALUES(9, 'Mal Porter', 'perecivel', 18.50);
insert into PRODUCT(ID, NAME, CATEGORY, VALUE) VALUES(10, 'Mal RIS', 'perecivel', 19.50);
insert into PRODUCT(ID, NAME, CATEGORY, VALUE) VALUES(11, 'Mal Session IPA', 'perecivel', 20.50);
insert into PRODUCT(ID, NAME, CATEGORY, VALUE) VALUES(12, 'Mal Brut IPA', 'perecivel', 21.50);
insert into PRODUCT(ID, NAME, CATEGORY, VALUE) VALUES(13, 'Mal Juice IPA', 'perecivel', 22.50);
insert into PRODUCT(ID, NAME, CATEGORY, VALUE) VALUES(14, 'Mal Lager', 'perecivel', 23.50);
insert into PRODUCT(ID, NAME, CATEGORY, VALUE) VALUES(15, 'Mal Bohemian Pilsner', 'perecivel', 24.50);
insert into PRODUCT(ID, NAME, CATEGORY, VALUE) VALUES(16, 'Mal Pilsner', 'perecivel', 25.50);
insert into PRODUCT(ID, NAME, CATEGORY, VALUE) VALUES(17, 'Mal Viena', 'perecivel', 26.50);
insert into PRODUCT(ID, NAME, CATEGORY, VALUE) VALUES(18, 'FunBeer Pale Ale', 'perecivel', 27.50);
insert into PRODUCT(ID, NAME, CATEGORY, VALUE) VALUES(19, 'FunBeer IPA', 'perecivel', 28.50);
insert into PRODUCT(ID, NAME, CATEGORY, VALUE) VALUES(20, 'FunBeer Double IPA', 'perecivel', 29.50);
insert into PRODUCT(ID, NAME, CATEGORY, VALUE) VALUES(21, 'FunBeer Imperial IPA', 'perecivel', 30.50);
insert into PRODUCT(ID, NAME, CATEGORY, VALUE) VALUES(22, 'FunBeer Juice IPA', 'perecivel', 31.50);
insert into PRODUCT(ID, NAME, CATEGORY, VALUE) VALUES(23, 'FunBeer Brut IPA', 'perecivel', 32.50);
insert into PRODUCT(ID, NAME, CATEGORY, VALUE) VALUES(24, 'FunBeer Hop Lager', 'perecivel', 33.50);
insert into PRODUCT(ID, NAME, CATEGORY, VALUE) VALUES(25, 'FunBeer Lager', 'perecivel', 34.50);
insert into PRODUCT(ID, NAME, CATEGORY, VALUE) VALUES(26, 'FunBeer Stout', 'perecivel', 35.50);
insert into PRODUCT(ID, NAME, CATEGORY, VALUE) VALUES(27, 'FunBeer RIS', 'perecivel', 36.50);
insert into PRODUCT(ID, NAME, CATEGORY, VALUE) VALUES(28, 'FunBeer Porter', 'perecivel', 37.50);
insert into PRODUCT(ID, NAME, CATEGORY, VALUE) VALUES(29, 'FunBeer Bohemian Pilsner', 'perecivel', 38.50);
insert into PRODUCT(ID, NAME, CATEGORY, VALUE) VALUES(30, 'FunBeer Red Ale', 'perecivel', 39.50);