insert into PRODUCT(ID, NAME, CATEGORY, VALUE, CREATE_DATE) VALUES(1, 'BodeBrown IPA', 'Perecível', 15.90, CURRENT_TIMESTAMP());
insert into PRODUCT(ID, NAME, CATEGORY, VALUE, CREATE_DATE) VALUES(2, 'Belorizontina', 'Perecível', 8.90, CURRENT_TIMESTAMP());
insert into PRODUCT(ID, NAME, CATEGORY, VALUE, CREATE_DATE) VALUES(3, 'Mal Pale Ale', 'Perecível', 12.50, CURRENT_TIMESTAMP());